target:
	gcc -o Printer Controller/Controller.hpp Exception/CustomExceptions.hpp Image/ColorImageConverter.hpp Image/ImageConverter.hpp Image/Image.hpp Helper.hpp PrinterHead/Motor.hpp PrinterHead/PrinterHead.hpp main.cpp 

clean:
	rm Printer
